# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-20 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContactManagerApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='MobileNo',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
